PhilanthropyDataCommons/front-end

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, package-lock.json, package.json, src/App.tsx, src/index.tsx, src/logger.ts, src/reportWebVitals.ts
Adopt Airbnb's ESLint configuration. This includes both their [base rules (including React rules)](https://www.npmjs.com/package/eslint-config-airbnb) and their [TypeScript rules](https://www.npmjs.com/package/eslint-config-airbnb-typescript). Also use the full [suite of recommended rules from the typescript-eslint plugin](https://typescript-eslint.io/linting/configs).
Add and configure [Pino](https://www.npmjs.com/package/pino) to log messages to the browser console - `INFO` and above during development, `ERROR` and above in production.
Clean up CI a bit, and fix several linter errors that show up with the stricter configuration.
See the individual commits for more detail.
To test, make sure that the appropriate logging happens during dev and production. In dev (`npm run start`), you …
=> Configure linter and logging

package-lock.json, package.json, public/_redirects, public/robots.txt, src/App.tsx, src/NotFound.tsx, src/Placeholder.test.tsx, src/Placeholder.tsx, src/index.tsx
Install [react-router](https://reactrouter.com/en/main), and set up a few routes: the existing placeholder content, and a 404 error page. Hopefully, this will be enough to set the pattern for @reefdog to work on adding more pages if needed, but we'll figure that out as we go!
Note that this has merge conflicts with #28; once that PR is merged, I'll rebase and resolve them.
Issue https://github.com/PhilanthropyDataCommons/data-viewer/issues/10 Scaffold routing and page construction
=> Add routing

src/stories/example/Button.stories.ts, src/stories/example/Header.stories.ts, src/stories/example/Page.stories.ts
This PR includes a small miss from #32.
I didn’t understand the importance of story placement, and left the example stories in the root `stories/` directory. Now, writing stories of my own for #12, I want these examples to live in `stories/example/`. So, this PR moves them there.
Affects #10 (which is already closed)
=> Move example stories into `example/` directory

.storybook/preview.ts, package-lock.json, package.json, src/components/Button.tsx, src/components/button.css, src/index.css, src/stories/Button.stories.tsx
This PR adds our `Button` component as designed in the Figma UI, along with all its various possible states. It also adds a Storybook story to demonstrate those states and allow playing with the various arguments.
We'll be adding more components, but I wanted to deliver this PR quickly to demonstrate patterns and get any overall feedback.
It includes some related global work, such as including global CSS in Storybook previews and affecting global styles and CSS variables. This work is arguably beyond this PR, but was a prerequisite to it and still relevant to the attached issue.
It also adds the [Heroicons](https://heroicons.com/) React library, which we use for icons (such as those in buttons).
**Testing:**
- `npm i` to get `@heroicons/react`
- `npm run storybook`
- Hit …
=> Create Button component and story

.env.example, public/index.html, src/App.tsx, src/components/Panel/Panel.css, src/components/Panel/PanelTag.tsx, src/components/ProposalDetailPanel.tsx, src/components/ProposalTable.tsx, src/components/Table/Table.css, src/index.css, src/pages/ProposalDetail.tsx, src/pdc-api.ts, src/stories/ProposalDetail.stories.tsx, src/stories/ProposalTable.stories.tsx
Add a new proposal detail page at `/proposal/:proposalId` that will fetch and display the details of the most recent version of that proposal. Visiting that page will automatically start the log in process if you are not yet logged in.
This is the first example of a pattern I'm proposing of separating display components (such as `<ProposalDetailPanel>`) from logic components that make API requests, transform API responses into the format display components expect, and so on. This separation will, I hope, make it easier to prototype new components, play with components in the storybook, and disentangle display logic from business logic. (This PR does not introduce any display logic, but an example would be the button that toggles between showing canonical field names and short codes; I'd …
=> Show proposal details

src/App.css, src/components/Navbar.tsx, src/components/User.tsx
This small PR offers two navbar improvements:
- Style the navbar login/user element like the others
- Arguably, this _shouldn't_ look like the others since it's not clickable. I agree, but it will (soon, hopefully) work as a link to basic user functionality like going to the settings and logging out (probably through a menu). I'm okay with this temporary weirdness. It doesn't have a `cursor:pointer` at least.
- Add a "feedback" item to the navbar for pilot participants to email the team
In the current state:
This PR will have conflicts with the #49 currently in flight, but it'll be simple to resolve.
Closes #61 
Closes #65
=> Improve navbar

.storybook/preview.tsx, src/App.tsx, src/components/Button.css, src/components/Navbar.tsx, src/components/ProposalListTable.tsx, src/components/ProposalListTablePanel.tsx, src/components/Table/Table.css, src/components/Table/Table.tsx, src/components/Table/TableRow.tsx, src/index.css, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts, src/stories/ProposalListTable.stories.tsx, src/stories/ProposalListTablePanel.stories.tsx, tsconfig.json
This PR uses some of changes in #46 to add a list page at `/proposals?page=1&count=20` that will retrieve the list of proposals from the API, transform the data, and display it. Clicking on a row will navigate to the proposal detail page.
Currently, the API does not provide the necessary details in the proposal list response, so we have to do an N+1 query where we get the details for each proposal in the list. This can take a long time and be a lot of traffic, but until the API offers more information, it's the only thing to do.
This has some pagination support, via the `page` and `count` query parameters, like `/proposals?count=25&page=3`. These parameters are passed along to the API. However, because the API also does not return any information about how many proposals or how many pages …
=> Proposal list page

src/App.tsx, src/components/ProposalDetailPanel.tsx, src/components/ProposalListTable.tsx
This PR implements the change from `/proposal/{id}` to `/proposals/{id}` for the proposal detail page. More justification in the issue and commit message.
To test, just make sure you can still navigate to the proposal detail page, and that the proposal list page still works (including with magic `count` changing).
Closes #63
=> Change proposal detail URL to `/proposals/{id}`

src/components/OffsiteLink.tsx, src/index.css
@jasonaowen came in with some excellent thoughts in his [review](https://github.com/PhilanthropyDataCommons/data-viewer/pull/69#pullrequestreview-1376548149) of the PR #69 after it had already been merged, but they are worth resolving. So this PR:
- Improves the legibility of the medium-dark gray we're using for our `.subtle` text (e.g., "Contribute on GitHub" graf)
- Invert the default for offsite links so they _don't_ open in a new window/tab by default.
=> Improve minor landing page issues

src/components/User.tsx, src/pages/Landing.tsx
Change the target of the two login buttons - in the `<User>` component of the navbar, and in the landing page - to go to `/proposals` instead of back to the landing page.
This does not affect the existing behavior of navigating to a secured page while signed out, which will continue to go through the login process and then redirect to the destination secured page.
Resolves #75 Go to Dashboard after initial login
=> Go to proposals page from log in button

src/pdc-api.ts
In PR [service#296](https://github.com/PhilanthropyDataCommons/service/pull/296), the return format of the `/proposals` API endpoint is changing from a top-level array of proposals to an object containing proposals under the `entries` key. It also returns the `total` number of proposals, which will allow us to do pagination, but that's separate work; for now, just update the parsing code to use the new format.
=> Handle API change to use bundles

src/App.css, src/App.tsx, src/components/AppHeader.tsx, src/components/AppMain.tsx, src/components/AppNavbar.tsx, src/components/Header.tsx, src/components/Panel/Panel.css, src/components/Panel/Panel.tsx, src/components/PanelGrid/PanelGrid.css, src/components/PanelGrid/PanelGrid.tsx, src/components/PanelGrid/PanelGridItem.tsx, src/components/PanelGrid/index.ts, src/pages/Landing.tsx, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/stories/PanelGrid.stories.tsx
This PR rewrites how we lay out the "full screen" style of panel so that we can support multiple adjacent panels with or without a sidebar panel.
Here is an example of what this would look like (though of course we would never show the same proposal twice like this):
There are a few small prerequisite commits that clean up the root element formatting. See individual commits for the lily-pads.
**Testing:**
Nothing in the app should appear to have changed; the layout should work just as before:
1. `npm start`
2. Make sure the landing page looks the same
3. Log in
4. Make sure the proposal list looks the same
5. Make sure a proposal detail page looks the same
6. `npm run storybook`
7. Check out the new `PanelGrid` story, especially the variations
Contributes to #62
=> Rewrite panel layout to support sidebar and multiple panels

src/components/Table/Table.css
Our table heads have top-borders. When the header is sticky, that top border used to remain visible when the header was sticky. That’s not ideal; a border is no longer needed to distinguish it from other content.
Before; watch the top of the panel as the header becomes sticky, how it looks like the shadow gets darker:
https://user-images.githubusercontent.com/4731/235010060-0b1a1060-49de-4a8b-a757-6c28d01a537a.mov
This PR makes the border defined via a CSS variable rather than statically, and sets the `top` property of the sticky header to the negative value of that variable so that the header scrolls that much out of view.
After; watch the top of the panel for how the shadow doesn't appear to get darker:
https://user-images.githubusercontent.com/4731/235010130-c40d2842-189e-4dff-8f85-c4d8 …
=> Improve sticky table headers

src/pages/Landing.tsx
It's better to keep the login landing page as simple and free of distractions as possible, since some newcomers might actually need to read it carefully to figure out what to do next.  We can put contribution information on other PDC pages, though: for example on informational pages about the PDC, and perhaps in the data viewer itself just elsewhere than the login landing page.
This resolves issue #88.
=> Remove contribution prompt from login landing page

src/components/ProposalListTablePanel.tsx
The field that contains the proposal name is `proposal_name`, but the code is currently using `proposal_title` (which doesn't exist).
This PR updates the default column list on the proposal table page so the proposal name appears.
Testing:
1. Before pulling this code, look at the `/proposals` page and notice that there is an empty column between the "Organization Operating Budget" and "Proposal Summary" columns.
2. Pull the code and reload; now there should be a "Proposal Name" column (with data for some proposals).
Closes #89
=> Fix proposal name field on table page

src/pdc-api.ts
Recently, [the API gained the ability to include all the necessary data in the `/proposals` endpoint](https://github.com/PhilanthropyDataCommons/service/pull/313), instead of only including IDs. As a result, we can stop making an additional N queries to `/proposal/{id}` to fill out the list, significantly improving load times.
We're still not using the [also-recently-introduced `total` field](https://github.com/PhilanthropyDataCommons/service/pull/296), which was introduced to support pagination, because instead we're doing [client-side search](https://github.com/PhilanthropyDataCommons/data-viewer/pull/84). Once [server-side search is ready](https://github.com/PhilanthropyDataCommons/service/pull/320), we'll be able to use that and implement pagination.
=> Use deep proposals data from API

src/components/FormElementGroup.css, src/components/FormElementGroup.tsx, src/components/Search.tsx, src/stories/FormElementGroup.stories.tsx
This PR adds a `FormElementGroup` component that we can use to conjoin form elements (buttons, inputs) into horizontal or vertical groups. It also applies that component to the search atop the proposal list table, so the search input and its submit button are visually bound.
**Before:**
**After:**
**Testing:**
- `npm start`
- Open the app in browser and confirm the search form looks like "After" above
- `npm run storybook`
- Open the Storybook in browser and look at the `FormElementGroup` docs and confirm they are 👍
=> Conjoin search input and button

src/components/ProposalListGrid.tsx, src/components/ProposalListGridItem.css, src/components/ProposalListGridItem.tsx, src/components/ProposalListGridPanel.tsx, src/stories/ProposalListGridPanel.stories.tsx
This PR adds the components necessary for displaying a list of proposals in a grid-based format suitable for narrow contexts like a sidebar.
[Screenshot redacted because it contains identifiers of PDC pilot participant organizations.]
To add it to a page, you simply:
```diff
- <PanelGrid>
+ <PanelGrid sidebarred>
+   <PanelGridItem>
+     <ProposalListGridPanel
+       proposals={…}
+   />
+   </PanelGridItem>
<PanelGridItem>
{Other panel}
</PanelGridItem>
</PanelGrid>
```
Issue #62
=> Add grid-based proposal list for sidebar

src/components/ProposalListGrid.tsx, src/components/ProposalListGridItem.tsx, src/components/ProposalListGridPanel.tsx, src/components/ProposalListTable.tsx, src/components/ProposalListTablePanel.tsx, src/interfaces/DataViewerProposal.ts
This PR creates a pattern for sharing TypeScript interfaces between files (`src/interfaces/Interface.ts`) and creates our first shared interface: `DataViewerProposal`. This is the interface that the DataViewer expects for a given proposal.
On its own, this PR changes nothing besides establishing the pattern with a single example. Future PRs will actually make more use of this shared interface.
**Testing:** Nothing should have broken or changed!
=> Share the DataViewerProposal interface

src/pages/ProposalList.tsx, src/pdc-api.ts
As I was working on supporting server-side search, and implementing the proposal list sidebar on the proposal detail page, I found that the API client code wasn't quite well suited to the task. Partly, this is because of previous changes, and partly because we're introducing new requirements.
In order to reduce the scope of these changes, make them now, before we implement the sidebar.
This is purely a refactor, and should not change the behavior of the application. See the individual commit messages for more details.
Issue https://github.com/PhilanthropyDataCommons/data-viewer/issues/15 Implement pagination on proposal lists
Issue #62 Add sidebar to Proposal Detail page
Issue https://github.com/PhilanthropyDataCommons/data-viewer/issues/83 Enable search
=> Refactor API client code

src/components/ProposalTable.tsx
The code still uses the "canonical" name internally, but fix it in the UI so that users will see the new term.
@reefdog, please merge this if it looks good - please don't wait for me if you want to include it in the demo!
Resolves #97 Rename "Canonical Field" to "Base Field"
=> Use 'Base Field' label in proposal detail page

src/map-proposals.ts, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx
Use the new `<ProposalListGridPanel>` component introduced in #94 in a sidebar on the proposal detail page.
See the individual commits for more details.
Resolves #62 Add sidebar to Proposal Detail page
=>  Add proposal list sidebar to proposal detail page 

src/map-proposals.ts, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts
In PR #99, we introduced a name for the display-centric models we are using. The name introduced, `DataViewerProposal`, is prefixed to distinguish itself from the type definitions for how the API represents data.
Rename the API-centric interfaces to include an `Api` prefix.
These new names make it clearer that we should not be using these interfaces so widely, but cleaning that up will be part of future work.
Issue #108 Rename shared TypeScript interfaces for clarity
=> Rename API interface type definitions

src/map-proposals.test.ts, src/map-proposals.ts
_This PR is an extraction of work and discussion from #101. It essentially replaces both #101 and #102._
This PR adds mock data and tests for the `mapProposals()` function, and then modifies that function to filter out blank strings when mapping API data to our internal data structure for proposal lists.
**Testing:**
1. `npm run test`
2. If you'd like, too, you can remove the `.filter((pair) => (pair[1].trim() !== ''))` line to see the test fail.
3. As this actually resolves the sidebar issue in #100, you can also `npm start` and load up a proposal detail page; no more proposals in the sidebar should have blank organization names.
**Incidentally…**
The intention of this PR was to extract some [great advice](https://github.com/PhilanthropyDataCommons/data-viewer/pull/101#discussion_r1185597 …
=> Filter blank proposal values

src/map-proposals.test.ts, src/map-proposals.ts, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts
Update the names in our code to follow the rename from "canonical fields" to "base fields", including the API endpoint. The user-facing strings used in the UI were previously changed in PR #105.
This must be deployed in coordination with https://github.com/PhilanthropyDataCommons/service/pull/334 , as deploying one without the other will break the front-end.
Issue https://github.com/PhilanthropyDataCommons/service/issues/275
=> Rename canonical fields to base fields

src/components/ProposalListGridItem.css, src/components/ProposalListGridItem.tsx, src/components/ProposalListTable.tsx, src/pages/ProposalDetail.tsx, src/utils/proposals.test.ts, src/utils/proposals.ts
_This PR changes some LOC that contain the "canonical" terminology changed by #113. Whichever PR is merged into `main` first — and I assume it's #113 but that's dependent on the API deployment — will cause conflicts with the other. That's fine, we'll resolve._
#112 resolved display of applicant name in the sidebar, but as documented in #109, there were still two more places that blank-string applicant names could mess up display:
- In the proposal list table's "Organization Name" column
- In the panel header atop proposal detail pages (and the `<title>` of that page)
This PR resolves both remaining places. It introduces a `getPreferredApplicantNameValues()` utility (yes, similar to the `getProposalValuesFromCandidates()` utility that I abandoned earlier) + tests, uses it, and then uses a …
=> Fix applicant name display

public/index.html, public/manifest.json
While preparing to tackle #71, I discovered a few Create React App boilerplate bits and pieces that deserved a quick cleanup but that I didn't want to muss up that impending PR with. So here they are.
This primarily removes some HTML comments that we don't need to be shipping to users (although I'm miffed we don't have a good place in our README for the `%PUBLIC_URL%` explanation, though it's easily Googleable) and corrects names/description metadata.
I considered just removing the WebManifest file because we have no intention of maintaining this as a mobile web PWA, but I can't convince myself of that.
=> Cleanup some React App boilerplate

package-lock.json, package.json
Since introducing Storybook in PR #28, they have [released 7.0](https://github.com/storybookjs/storybook/releases/tag/v7.0.0), and a dozen more point releases. Update all our Storybook dependencies to their latest versions:
npm install --save-dev \
@storybook/addon-essentials@latest \
@storybook/addon-interactions@latest \
@storybook/addon-links@latest \
@storybook/blocks@latest \
@storybook/preset-create-react-app@latest \
@storybook/react@latest \
@storybook/react-webpack5@latest \
@storybook/testing-library@latest \
storybook@latest
=> Upgrade Storybook from 7.0.0-beta.62 to 7.0.12

src/components/Panel/Panel.css, src/components/ProposalListTablePanel.tsx, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts
Rather than always loading the full list of proposals from the API and doing basic string matching locally, instead use the recently introduced search API. The server search API includes such fanciness as word stemming (so that a query for "summaries" would match a proposal containing "summary") and operators (like "a OR b" which would match proposals containing either).
Note that we have not yet implemented pagination, so this is somewhat of a tradeoff: the initial page load will get the full list of proposals, and searching will cause another server round trip, and clearing the search will cause a third round trip. However, this is a necessary step on the way to pagination.
This should not be deployed (read: merged) until https://github.com/PhilanthropyDataCommons/service/pull/320 and …
=> Use server search API

src/utils/proposals.ts
This PR just fixes a typo in a function comment (`returns iterates`), but then lightly re-formats it for readability.
Given it's just a comment the approval request here is purely obligatory.
=> Clean up `getPreferredApplicantNameValues` comment

src/components/ProposalListTable.tsx, src/pages/ProposalDetail.tsx
This PR simplifies our display of `proposal_name` from a cascade to other fields to just a simple field display.
Because of this change, I went ahead and made the simplification @jasonaowen [suggested](https://github.com/PhilanthropyDataCommons/data-viewer/pull/114#discussion_r1192764099) in his review of #114.
**Testing:**
The cascade that this PR removes wasn't working as designed anyway, since the field that `proposal_name` was falling back to (`proposal_title`) [had already been renamed](https://github.com/PhilanthropyDataCommons/service/issues/284#issuecomment-1531799718) without the viewer knowing / being updated. (Oops.) Thus, there's no A/B (`main` / this branch) comparison you can make to prove anything.
So: just load up the proposal detail page for any proposal with a …
=> Don't cascade `proposal_name` to other fields

src/components/Table/Table.css
This PR replaces the draconian `white-space: nowrap` on row headers with a more sensible min-width of 25%.
While this may still not look perfect in all scenarios, it looks natural in all scenarios I tested it against, and avoids the problem where very long row headers can generate undesired layout.
**Before:**
**After:**
Closes #168 Long field labels break table formatting
=> Allow table row headers to wrap but with min-width

src/components/ProposalDetailPanel.tsx
For speedy dev navigation between proposals, we offer next/previous buttons on the proposal detail panel. These take up quite a lot of space, however.
This change condenses them by hiding the labels and using the `FormElementGroup` wrapper.
**Before:**
**After:**
=> Condense next/previous proposal buttons

src/components/Dropdown/Dropdown.css, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownMenuLink.tsx, src/components/Dropdown/DropdownMenuText.tsx, src/components/Dropdown/index.ts, src/stories/Dropdown.stories.tsx
This PR adds a `Dropdown` component, used for generating dropdown menus from button-like triggers:
https://github.com/PhilanthropyDataCommons/data-viewer/assets/4731/2ab5c95a-0d36-4fbf-afe3-55897c2e5671
This implementation is specific to our current needs and doesn’t offer the flexibility one would want from a general-purpose dropdown library. That’s fine until we have more use cases.
**Testing:**
As this isn't yet implemented on any page, you'll need to run the Storybook to see it.
Issue #23 Create applicant detail page
=> Add Dropdown component and story

src/components/Panel/Panel.css, src/components/Table/Table.css
This PR includes a few small change to panel elements, all of which improve their layout and behavior in a large number of real-world circumstances:
1. In narrow panels with a long panel tag — especially long enough to wrap — the icon in the panel tag no longer shrinks. (The layout savings are very minimal compared to the UI weirdness of the shrinking.) Also, panel tag text line height is reduced, for a nicer-looking layout when it wraps.
2. Some extraneous padding was removed from around panel titles.
3. Rather than the entire panel scrolling when the panel body was too large, now only the body itself scrolls. The header remains fixed. This resolves the issue in #86 where wide panel body tables were pushing the panel actions out of view, and also allows the header to remain in-view while …
=> Improve panel layouts

src/components/Button.css
This PR improves button display in two ways:
- Don’t allow the icon to shrink; it’s small, there’s no need
- Don’t allow button text to wrap; if we find ourself in this scenario, something else should probably change. (E.g., responsively hiding the text portion of the button, reducing wording, etc.)
**Before,** this was (incorrectly) possible:
**Now,** the interface insists upon maintaining this:
Why? Because too often buttons were in contexts (such as a flex layout) that _suggested_ they should reduce in size, when we didn't really want them to. Instead, we tend to want _other_ elements to get out of the way before we modify button layout. If we find some part of the interface where our buttons really are too big, we should address it some other way.
=> Maintain consistent internal button positioning

src/components/Dropdown/DropdownMenuLink.tsx, src/stories/Dropdown.stories.tsx
This PR ensures a dropdown menu closes when a link within is clicked.
@jasonaowen rubber-ducked for a while on where this should live before settling on binding directly to the `Link` within each `DropdownMenuLink` component, and targeting the parent `Dropdown` component using native DOM traversal rather than refs or passing a handler in as a prop. This isn't the most React-idiomatic approach, but it avoids a larger set of complications.
It also fixes a missing key issue in the Dropdown Storybook that I hadn't noticed before.
**Testing:**
1. Go to [`main`'s Dropdown Storybook](https://pilot.philanthropydatacommons.org/storybook/?path=/docs/stories-dropdown--docs)
2. Open a dropdown and click an item inside
3. ❌ Note that the dropdown menu doesn't close!
4. Go to [this branch's Dropdown …
=> Close dropdown when a child link is clicked

package-lock.json, package.json, src/App.tsx, src/components/Button.tsx, src/components/DataPlatformProvider/DataPlatformProviderLoader.tsx, src/components/DataPlatformProvider/DataPlatformProviderPanel.tsx, src/components/DataPlatformProvider/DataPlatformProviderTable.tsx, src/components/Panel/ClosablePanel.tsx, src/components/Panel/Panel.css, src/components/Panel/index.ts, src/components/ProposalDetailPanel.tsx, src/components/ProposalTable.tsx, src/pages/ProposalDetail.tsx, src/pdc-api.ts
_This commit ladders off #166._
This PR adds the components and page required to show data platform provider data:
Some of these commits can be used as-is (pending review), but others are intended only to demonstrate patterns and usage. I expect @jasonaowen will want to take a slightly different tactic for generating the `ProposalDetailWithProvider` page, for instance.
**Testing:**
1. Go to any proposal detail page
2. Use the new "Data providers" dropdown to open a provider panel
3. Data is placeholder, but the close button should work and the link to Candid and Charity Navigator _might_ work. (The URL format is correct, but it's possible the platform doesn't have that EIN.)
**Notes:**
- This is quite messy but a start.
- Doesn't do anything conditional based on whether we have data from …
=> Add data platform panel

src/components/Button.css, src/components/DataPlatformProvider/DataPlatformProviderPanel.tsx, src/components/Panel/ClosablePanel.tsx, src/components/Panel/Panel.css, src/components/Panel/PanelBody.tsx, src/components/ProposalDetailPanel.tsx, src/components/ProposalListGridPanel.tsx, src/components/ProposalListTablePanel.tsx, src/index.css, src/pages/Landing.css
This PR reformats our `PanelBody` components so that, by default, they have an internal padding that matches the `PanelHeader` padding. This makes them more usable as-is without any further styling. The padding can be removed with the new `padded` prop, which removes the padding for a more "full-panel" interface that we often use.
This required adding the `padded` prop to multiple components and changing the `ClosablePanel` component to pass it through as well.
**Testing:**
- Most panels should look the same as they did before
- The "Loading…" and "No data found" versions of the data platform provider panels should now appear with padding, so the messages are no longer flush with the edge
**Regression note:**
There is one big regression that I don't like and can't figure out: when the …
=> Add padding to panel bodies by default

.github/dependabot.yml, package-lock.json, package.json
When we enabled Dependabot version upgrades in this repo, one of the first things it did was hassle us about `@types/node`: #125. That brought to my attention the fact we were using the wrong version of `@types/node`, given that we're targeting Node.js 18, so fix that, and also configure Dependabot not to give us major version upgrades for that package.
=> Use types for Node.js 18

src/components/ProposalListTable.tsx
This PR enables text selection on the proposal list table by modifying the click handler to only navigate to the proposal detail page if it can tell the "click" is not just the end of a text selection.
Note: This intentionally only applies to the proposal list **table**, not the grid/sidebar. That's because the need to select text in the sidebar is low, while supporting text selection within a `Link` component (aka `a` element) would conflict with default browser behavior like the ability to drag a link to the toolbar to bookmark or open a new tab.
**Testing:**
1. On `main`, go to the Dashboard
2. Attempt to select text in any of the proposal rows
3. ❌ Be stymied because the page navigates to the proposal detail page.
4. On this branch, go to the Dashboard.
5. Attempt to select text in …
=> Allow text selection on proposal list table

src/components/ProposalDetailPanel.tsx
_This PR ladders off #200; otherwise, removing this block of code would cause the linter to want me to remove the `proposalId` reference, but #200 uses that reference. It would cause unnecessary churn to have started this off `main`._
This PR removes the dev-only next/previous arrows in the top-right of the proposal detail panel. Now that we have a sidebar, we no longer need this convenience.
**Testing:**
Because this is a dev feature, testing must be done when running the app in dev mode (like, locally). The deploy preview isn't sufficient.
1. On `main`, go to a proposal detail page.
2. Note the left/right arrows in the top right of the detail panel.
3. Switch to this branch and check again.
4. ✅ Note the absence of the left/right arrows.
Closes #172
=> Remove next/prev proposal buttons

.github/dependabot.yml, package-lock.json, package.json
Storybook has a bunch of components to choose from. Those components should be updated alongside each other; mixing different versions is not a good practice, and ends up causing a lot of PR thrash and email spam. Additionally, since Dependabot will only open a certain number PRs at a time, these PRs can block other, more important updates.
The team working on Dependabot is considering a feature to allow for grouped updates, where we'd be able to specify that all of the Storybook components should be updated at the same time, rather than separate PRs. Until that feature is implemented, though, tell Dependabot to ignore Storybook.
Use the [upgrade script](https://storybook.js.org/docs/react/configure/upgrading#page-top) to update all its dependencies to …
=> Upgrade Storybook, and tell Dependabot not to

src/App.css, src/components/Button.css, src/components/FormElementGroup.css, src/index.css, src/stories/Button.stories.tsx
Prior to this PR, the only interaction that button/form elements had was to gain a garish blue outline when focused. This PR:
- Adds hover state (slight darkening of background)
- Uses the hover state as the focus state
- Adds the outline to the active state (when the button is being pressed)
- It pointedly does _not_ use the outline for the focus state anymore, since that remains after click (until the element is "blurred" but clicking/interacting elsewhere), and the outline is too large of a UI element to leave vestigially.
It also removes the focus ring from the app navbar, which now just has a simple background color change for both hover and focus.
**Testing:**
- `npm run storybook` and tinker with the [Story](http://localhost:6006/?path=/docs/stories-button--docs)
- `npm start` and …
=> Improve interactive button styling

RECENT_CHANGES.md, src/pages/Landing.tsx
This PR adds the `RECENT_CHANGES.md` document we discussed in #39, populates it with some suggested content, and modifies the landing page to link to it. (Note that this link won't actually working until this PR is merged in, but I don't think that weirdness should stop us from treating this as a single PR.)
Please feel free to suggest edits/additions to the recent changes! I'm tagging everyone on this review because suggestions for populating the change list are welcome from anyone. Please do read [this comment](https://github.com/PhilanthropyDataCommons/data-viewer/issues/39#issuecomment-1603439095) first, which explains what sort of changes we want to record here. (It's not a technical CHANGELOG.) 
Closes #39
=> Add RECENT_CHANGES document and link to it

RECENT_CHANGES.md
PR #249, which improved button styling, was done simultaneously with the creation of the `RECENT_CHANGES.md` doc. Thus, we weren't able to add a note about it until after that doc existed.
Now it does, so retroactively adding it.
=> Add "improve button styling" to RECENT_CHANGES

.github/dependabot.yml
Configure Dependabot to create pull requests during business hours.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletime
=> Set Dependabot to open PRs at noon Pacific

.github/dependabot.yml
We have two sets of dependencies that should only ever be updated together, and never separately. React updates rarely, but we'd previously disabled Dependabot updates to Storybook because there were so many components and Dependabot would open a PR for each.
However, GitHub [recently](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/) released support for [grouped updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)! With this feature, we can define groups that Dependabot should open one collective PR for, rather than separate PRs.
Define groups for React and Storybook, and allow Dependabot to update Storybook again.
=> Group Dependabot updates to Storybook and React

.env.example, README.md, package-lock.json, package.json, src/components/ProposalListGrid.tsx, src/components/ProposalListGridItem.tsx, src/components/ProposalListGridPanel.tsx, src/components/ProposalListTable.tsx, src/components/ProposalListTablePanel.tsx, src/interfaces/FrontEndProposal.ts, src/logger.ts, src/pages/Landing.tsx, src/utils/proposals.test.ts, src/utils/proposals.ts
Update all the places that the repository name occurs. This does not update any in-app user-facing strings, per @kfogel's [suggestion](https://github.com/PhilanthropyDataCommons/data-viewer/issues/315#issuecomment-1716320859).
Issue #315 Choose new name for Data Viewer
=> Rename repo from data-viewer to front-end

README.md, RECENT_CHANGES.md, public/index.html, public/manifest.json, src/components/AppNavbar.tsx, src/pages/Landing.tsx
This PR replaces all user-facing references to the "data viewer" with context-appropriate variations of "the Philanthropy Data Commons". While in the pilot phase, we continue to append the word "pilot", but we can remove that word whenever we want without further rewriting or copy edits.
It also replaces the project README's auto-generated title with a more descriptive one.
Closes #315
=> Replace user-facing references to "data viewer"

RECENT_CHANGES.md, public/index.html, public/manifest.json, src/components/AppNavbar.tsx, src/pages/Landing.tsx
This PR removes the term "pilot" from around the site.
It doesn't close the attached issue, because to complete the task we'll need to configure the site to be hosted at a different subdomain; however, that won't require any further code changes, so this can be merged independently of that transition.
**Testing:**
1. Open the deploy preview URL (see below)
2. Verify that the page title (window/tab) and the landing page copy don't say "pilot"
3. Click on some of the email links and verify the subject lines don't contain the word "pilot"
Affects #333
=> Remove “pilot” terminology

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This PR adds the `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` files that govern contributions and participant conduct.
As per multiple discussions, individual repos will contain links to the shared versions in the PDC `.github` repository, plus any repo-specific instructions.
Closes #251
=> Add Contributing and Code of Conduct files

src/App.tsx, src/Layout.tsx, src/index.tsx
The React Router documentation [recommends](https://reactrouter.com/en/main/routers/create-browser-router) using the new data router approach for all projects. This is a fairly faithful and simple refactoring following the [migration guide](https://reactrouter.com/en/main/upgrading/v6-data). It should have all the same behavior as the existing application, and would allow us to use the new APIs that are only available in data router apps.
=> Refactor to new react-router data router

.github/workflows/build.yml
In a bit of what I presume was copy-pasta, the job for building the application was misnamed. This text is user-visible in the GitHub pull request status, where it lists the checks that have passed or failed.
This recently confused me!
=> Fix GitHub Actions check name

src/components/AppNavbar.tsx
We are using Netlify to build and deploy the front-end, and it is able to deploy pull requests to temporary domains. Often, one of the things we want to check on a deploy preview is that our components look good in Storybook - and, indeed, that Storybook is working correctly.
Previously, after Netlify gave us a deploy preview, we would follow the link it posted in the PR and then manually add `/storybook` to the end. Now, there can be a link in the app!
The link only renders when the app is built with the environment variable `REACT_APP_SHOW_STORYBOOK` set to the value `true` - otherwise, and by default, the new navbar icon will not be shown. Netlify allows for deploy-preview-only environment variables, and I have configured it to activate this feature.
Note also this won't really work …
=> Show Storybook icon on deploy previews

src/App.tsx, src/components/AddDataInstructions.tsx, src/components/BaseFields.tsx, src/components/BulkUploader.tsx, src/pages/AddData.tsx, src/stories/AddDataInstructions.stories.tsx, src/stories/BaseFields.stories.tsx, src/stories/BulkUploader.stories.tsx
Build out the route, an initial page, and a few placeholder components for the new Add Data page, and wire the placeholder components into Storybook.
There are still several open questions that this does not attempt to resolve, including:
- what information do we get from the API about previous bulk uploads?
- what exactly do we want the prose to say?
- how exactly will the upload component work?
and other such future problems. For now, lay a foundation for additional work to build on.
Note that this is built on top of #421, so this is marked as a draft PR until that is merged and the merge base is reset to `main`.
Issue #409 Create bulk upload route and page
=> Add initial outline of data page

RECENT_CHANGES.md, _redirects
Configure Netlify to redirect requests.
Netlify allows [redirects between the domains of an app](https://docs.netlify.com/domains-https/custom-domains/multiple-domains/#domain-redirects) by using the [`_redirects` file](https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects).
This should not be merged until DNS is configured and confirmed working!
Issue #333 Change subdomain from pilot to app
=> Redirect from pilot.pdco to app.pdco

src/components/BulkUploaderFilePicker.css, src/components/BulkUploaderFilePicker.tsx, src/components/Spinner.css, src/components/Spinner.tsx, src/index.css, src/stories/BulkUploaderFilePicker.stories.tsx, src/stories/Spinner.stories.tsx
This PR adds the component for picking a file from the filesystem to use for bulk upload. It supports both drag-and-drop and clicking to load the OS's native file-picker. (We don't call attention to the latter; it's a fallback. You can also activate it  via keyboard by tabbing to the component.) There is also some very basic validation, with TODOs for more/better.
https://github.com/PhilanthropyDataCommons/front-end/assets/4731/27de9f43-067b-4219-8383-0cc52fcaea11
This implementation is focused on our needs for the bulk uploader. I've thought about how it can be made into a more generic uploader, but decided we should wait until we have a second use case. Still, if there are obvious ways we can prepare for the future with a different component architecture, please suggest them. …
=> Create bulk upload file-picking component

src/components/AddDataInstructions.css, src/components/AddDataInstructions.tsx, src/components/BaseFields.css, src/components/BaseFields.tsx, src/map-proposals.test.ts, src/pages/AddData.tsx, src/pdc-api.ts, src/stories/BaseFields.stories.tsx
Add the text that @reefdog wrote describing the use of the add data page, and show the list of base fields.
Unfortunately, we have some very long base field `shortCode`s, so the first column is wider than in the mockup in #418. As a follow-up, we may wish to introduce a truncation toggle as we did on the proposals list. Additionally, or possibly alternatively, we are meaning to do a base field review, so maybe we'll fix this display challenge by fixing the data.
Note that this code assumes the API is giving us descriptions, but that change has not yet been deployed to production. That works out because a missing key lookup evaluates to null, which is rendered just the same as the empty string the API would give us until descriptions have been written.
To review, manually edit your URL to …
=> Add data instructions and base fields table

src/components/AddDataInstructions.tsx, src/components/Panel/Panel.css
This PR tweaks the bulk upload instructions to:
- offer less negative language by default
- include required field notice
- hold the user's hand by (smoothly) scrolling to the base field keys
Closes #463
Closes #464
=> Improve base field guidance

.editorconfig, src/components/BulkUploaderFilePicker.tsx, src/pages/AddData.tsx, src/pdc-api.ts, src/stories/BulkUploaderFilePicker.stories.tsx
This PR:
- Adds a file handler to the file picker component
- Creates a presigned POST request
- Uploads the bulk upload to the service
- Marks the upload as complete once it is
- Marks the file picker with an error if the upload fails
It does not:
- Refresh the BulkUpload history with the new upload; user must refresh.
- Opened as: #527
TODO:
- ~Add RECENT_CHANGES note~ Edit: Actually, we shouldn't do this until we actually want users to use it, I.e. #438
🚨 **Reminder:** The `service` repo will need a production deployment before this is merged in. The [currently-deployed API](https://api.philanthropydatacommons.org) doesn't have `/bulkUploads` routes. 🚨
Closes #412
Closes #528
=> Upload bulk uploads to the API

src/components/AddDataInstructions.css, src/components/BulkUploadList.css, src/components/BulkUploadList.tsx, src/components/BulkUploadListItem.css, src/components/BulkUploaderFilePicker.css, src/components/BulkUploaderFilePicker.tsx, src/components/NewBulkUploadPanel.css, src/components/NewBulkUploadPanel.tsx, src/components/Panel/Panel.css, src/components/Panel/PanelHeader.tsx, src/index.css, src/pages/AddData.css, src/pages/AddData.tsx, src/stories/NewBulkUploadPanel.stories.tsx
_This PR is branched off of #519. Don't merge this in until that one has been merged + this one's base changed to `main`._
This large PR reformats the bulk upload page following the designs of #477, although it does not yet include the ability to actually drill into bulk upload history (to, e.g., view full error details).
<details>
<summary>Click to view before/after screenshots…</summary>
**Before:**
**After:**
</details>
- Moves the uploader into the main panel
- Changes the uploading instructions (and layout)
- Adds "New bulk upload" nav link atop sidebar
- Adds "Bulk Upload History" header above sidebar items
- Removes padding from bulk upload history sidebar items
- Additional minor improvements to typography and layout that were more apparent alongside this work
**Testing:**
1. `npm …
=> Implement new bulk upload page design

src/components/DataPlatformProvider/DataPlatformProviderLoader.tsx, src/components/NewBulkUploadPanel.tsx, src/pages/AddData.tsx, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts, src/stories/NewBulkUploadPanel.stories.tsx
This PR changes the API hooks so that they expose the ability to re-run a given API call at a later time.  It also utilizes that new functionality to re-run the bulk upload list lookup every time the user creates a new bulk upload.
Resolves #527
=> Refresh upload history

src/pages/AddData.tsx
On the bulk upload page, when a user uploads a new file, the entire BulkUploadList component re-renders. This was fixed by using react state for the BulkUploads array that contains the metadata of the uploaded files. Now, on component update, only changed/added list items are re-rendered. 
Closes #572 
Testing:
Open dev instance
Log in 
Go to the Add Data page
Inspect the Bulk Upload History panel, and select a pre-existing component in the react-dev-tools inspector
Upload a new file, and verify that the pre-existing component was not re-rendered
=> Fix Bulk Upload List Refresh on File Upload 

.github/dependabot.yml
This PR changes dependabot to only run once a week for npm dependencies (I left the github ones at the same daily cadence since they are infrequent)
Resolves #591
=> Decrease dependabot frequency

src/pages/AddData.tsx
On the bulk upload page, when a user uploads a new file, the BulkUploadListItem will not update it's status until the page is refreshed. I have added a poll in the form of an interval set inside of the AddData page's useEffect hook that will poll the API every 2 seconds(a time amount I am open to changing, depending on group thought) and rerender any BulkUploadListItem's with changed status. I also added a callback function to the hook that clears the interval, so as to end the interval if the component ever dismounts. Based on my research this seems to be the convention when using setInterval.
Closes #415
Testing:
Open dev instance
Log in
Go to the Add Data page
Check the network tab in browser dev tools to verify a call to the backend is happening every 2 seconds
Upload a new file, …
=> Add Poll API for bulk upload processing

src/components/ProposalDetailPanel.tsx, src/stories/Dropdown.stories.tsx
Heroicons renamed one of their icons that we use. The old name has been deprecated and so intellisense ~strikes it out~. Let's replace.
**Testing:**
1. Open the dropdown in the [production "Dropdown → With Menu Item Icons" story](https://app.philanthropydatacommons.org/storybook/?path=/story/stories-dropdown--with-menu-item-icons) and note the icon.
2. Open that same dropdown in [this deploy preview's Storybook](https://deploy-preview-594--philanthropy-data-commons-viewer.netlify.app/storybook/?path=/story/stories-dropdown--with-menu-item-icons) and check the icon.
3. ✅ It's the same icon!
Closes #586
=> Replace deprecated Heroicons icons

.github/dependabot.yml
This PR adds an eslint grouping in dependabot so eslint related packages will get updated at the same time.
=> Group eslint dependencies in dependabot

src/components/AppNavbar.tsx, src/components/Dropdown/Dropdown.css, src/components/User.tsx
This PR changes our navbar icons to be outlines when inactive and solid when active. It also moves the Developer menu to "last" (farthest right) on the navbar, except that the user menu remains the _farthest_ right (as per standard design).
**Before:** Logged out, on the Landing page:
**After:** Logged out, on the Landing page:
**Before:** Logged in, on the Dashboard page:
**After:** Logged in, on the Dashboard page:
**Testing:**
Navbar icons should be outlined by default. They should turn solid when:
- **Dashboard** and **Add Data**: solid when you are actually on those page
- ✋ These will also be blue
- **About** dropdown, **Developers** dropdown: solid when the menu is open
- **User** icon: solid when you are logged in
Closes #606
Closes #660
=> Improve navbar icons and order

.github/dependabot.yml
ESLint 18 has dependencies that are evidently incompatible with our current dev framework, Create React App. Until that’s replaced (#498), let’s disable Dependabot updating ESLint past 17.x.
As a Dependabot configuration change, there's not really a way to test this besides merging it in and observing Dependabot behavior. But eyes on it (and verifying the strategy) are appreciated!
Note that I've also created issue #665 to capture _removing_ this ignore rule once #498 is resolved and ESLint v18 compatibility ensured.
Closes #664
=> 😈 Configure Dependabot to ignore ESLint major updates

src/components/OrganizationDetailPanel.tsx, src/components/OrganizationListTable.tsx, src/components/OrganizationListTablePanel.tsx, src/components/ProposalListTable.tsx, src/components/ProposalListTablePanel.tsx, src/pages/OrganizationDetail.tsx, src/pages/ProposalList.tsx, src/pdc-api.ts, src/utils/baseFields.ts
This pull request adds a proposals table to the organization detail page. Currently it will load all proposals for any organization, but once organizations are linked to proposals another edition will be necessary to display related proposals.
Closes #612 
Testing:
- run pdc service
- populate service with at least 1 organization and 1 proposal
- run front-end
- navigate to 'organizations' on the front-end
- click an organization
- verify that the detail page you are redirected to has both the organization information and all proposals in the database displayed in a table below.
=> Add Proposals table to Organization Detail Page

package.json
This PR updates our lint command so that it will return an error code if there are any warnings.  Prior to this commit our CI would pass even if there were warnings (e.g. console.log statements)
Resolves #523
=> Fail eslint on warning

src/App.css, src/components/AppNavbar.tsx, src/components/BulkUploadList.css, src/components/Dropdown/Dropdown.css, src/components/Dropdown/DropdownMenuLink.tsx, src/components/Dropdown/DropdownMenuLinkDescription.tsx, src/components/Dropdown/index.ts, src/components/ListGrid.css, src/index.css, src/stories/Dropdown.stories.tsx
This PR improves the look of our navbar dropdowns in preparation for the user menu dropdown (#618).
Before:
After:
<details>
<summary>If you think that's a stylistic regression…</summary>
Maybe some of you will think "Ah, but, that's less attractive!" And you're not wrong, but, the new format looks better when interleaved with more traditional dropdown items (which we don't want to always force into the "small uppercase" format):
https://github.com/PhilanthropyDataCommons/front-end/assets/4731/7097f3dc-e41b-4ed1-95e1-9700e8c5ccef
</details>
Along for the ride come some text accessibility improvements and an improvement to the `:focus` outline when keyboard-navigating the menu.
**Testing:**
You can test this via the [deploy preview](https://deploy-preview-676--philanthropy-data-commons-view …
=> Improve display of navbar dropdowns

src/components/AppNavbar.tsx, src/components/Dropdown/Dropdown.tsx, src/stories/Dropdown.stories.tsx
Previously, you could "trick" the navbar into having multiple dropdowns open at a once by keyboard-navigating from an open menu to an adjacent trigger. (See video in #679.)
Since our Dropdowns use the HTML `<details>` element behind the scenes, and that element supports a [`name` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#name) precisely for adding accordion-like "just one open item at a time" behavior, this PR adds our own `name` prop to the `Dropdown` component to support the same thing.
**Testing:**
Preface: Firefox doesn't yet support this attribute, so you'll need to test this in Safari or Chrome. Also, the only way to really trigger this "bug" (and thus the only way to confirm it's fixed) is if your browser/OS combo allow tabbing through links. For …
=> Limit navbar to only one open dropdown at a time

src/App.tsx, src/components/OrganizationDetailPanel.tsx, src/components/OrganizationProposal/OrganizationProposalLoader.tsx, src/components/OrganizationProposal/OrganizationProposalPanel.tsx, src/components/Panel/ClosablePanel.tsx, src/components/ProposalListTable.tsx, src/components/Table/Table.css, src/components/Table/TableRow.tsx, src/pages/OrganizationDetail.tsx, src/pages/ProposalDetail.tsx, src/utils/proposalFields.ts
This PR adds a side panel to the organizations detail page that is opened via clicking on a proposal in the Organizations proposal table. On click of the expansion icon, the user will be redirected to the related proposals detail page.
Closes #613 
Testing:
1. Start PDC front-end
2. Populate the database with (at least) 1 organization, 1 proposal, and 1 OrganizationProposal relating the organization and proposal
3. Navigate to `/organizations/1`
4. Click on the related proposal in the Organization's proposal table
5. Verify that the side panel opens on click, closes on click of the X icon, and redirects to the proposal's detail page on click of the expand icon
=> Add proposal side panel to organizations page

src/components/OrganizationListTablePanel.tsx, src/components/Table/Table.css
Prior to this PR, the org table was incorrectly padded.
This PR fixes the padding, and resolves a display issue that is only noticeable once the padding was fixed.
**Testing:**
- In production, to go https://app.philanthropydatacommons.org/organizations
- ❌ Note the lack of padding around the "No data available" message
- On a local `main` with organizations data, go to `/organizations`
- ❌ Note the padding around the table
- Now, on this branch, repeat the above — well, however you can to trigger both states
- ✅ Note that the "No data available" message has padding, while the table doesn't
Closes #688
=> Fix display issues with organizations tables

src/components/NewBulkUploadPanel.tsx
Tiny PR that removes some out of date instructions on our Bulk Upload page.
**Testing:** Just make sure the `proposal_submitter_email` requirement is gone from the bulk upload page. For extra credit, actually upload a CSV without a `proposal_submitter_email` column to make sure the instructions are still valid.
Closes #690
=> Remove `proposal_submitter_email` bulk upload note

src/components/AppNavbar.tsx, src/components/NewBulkUploadPanel.tsx, src/components/OrganizationDetailPanel.tsx, src/components/Panel/Panel.css, src/components/ProposalListTable.tsx, src/index.css, src/pages/Landing.tsx
Now that we have org pages, and show proposals on those org pages, a couple of changes were necessary for clarity. This PR:
- Changes the default order of proposal table columns so that proposal-related columns come before org-related columns
- Adds a "Proposals" header to the proposals table on the org detail page
- Adds a fallback message instead of rendering an empty table on the org detail page, when an org has no proposals
- Renames Dashboard to Proposals (🎉) and only shows it to authenticated users
- We still don't want to add an Organizations item to the navbar (#604) until users are actually going to start seeing orgs in the PDC, which means https://github.com/PhilanthropyDataCommons/service/issues/902
- Sets a standard set of heading font-sizes (and margins), and updates a few …
=> Distinguish orgs from proposals better

src/App.tsx, src/pages/AddData.tsx, src/pages/OrganizationDetail.tsx, src/pages/OrganizationList.tsx, src/pages/ProposalDetail.tsx, src/pages/ProposalList.tsx
This PR moves securing pages from the components themselves to the app router. There should be no functional changes from the current system, it's just prerequisite work for the public pages — but a significant enough change to justify its own PR and review.
This is a syntax [explicitly demonstrated by our authentication library](https://github.com/AxaFrance/oidc-client/tree/main/packages/react-oidc#how-to-secure-a-component--hoc-method), which we did originally [consider but discarded](https://github.com/PhilanthropyDataCommons/front-end/pull/106#discussion_r1186521329) for reasons that I _think_ no longer apply. (We weren't using `<RouteProvider>` at the time.)
This will let us selectively secure routes that lead to the same page component that unprotected routes lead to. Specifically, …
=> Relocate page security to router

src/App.css, src/App.tsx, src/Layout.tsx, src/components/AppBanner.tsx, src/components/Button.css, src/components/Button.tsx, src/components/OrganizationDetailPanel.tsx, src/components/OrganizationProposal/OrganizationProposalLoader.tsx, src/pages/OrganizationDetail.tsx, src/stories/Button.stories.tsx
This PR adds publicly-accessible organization views (list and detail pages). It customizes the detail pages so that parts of the page that public visitors shouldn't see or use — data provider buttons/panels, proposal table/panels — are hidden. It also adds a banner atop the site that alerts public visitors that they may only be seeing a subset of the available data. This banner doesn't appear on the home page, just internal pages.
There are also a couple of minor clean-up commits to related code that are minor (and related) enough that I'd like to include them.
**Testing:**
1. On `main`/production, try to access `/organizations` or an organization detail page while logged out.
2. ❌ Note that you are redirected to the login form.
3. On this branch, do the same.
4. ✅ Note that despite not …
=> Add public org views

RECENT_CHANGES.md, src/components/AppNavbar.tsx, src/components/Button.css, src/components/Button.tsx, src/components/User.tsx, src/pages/Landing.css, src/pages/Landing.tsx
We already had org table and detail pages, but you had to know the URL to get to them. We're actually ready for folks to use them, so… this PR:
- Adds an Organizations item to the navbar (even when logged-out)
- Updates the landing page with a pre-login link to the orgs and a post-login link to proposals and orgs
<details>
<summary>Click to view before/after comparison screenshots…</summary>
**Before, logged out:**
**After, logged out:**
**Before, logged in:**
**After, logged in:**
</details>
**Testing:**
- ✅ See the Organizations item in the navbar (whether logged in or not)
- ✅ See the new landing page button options (in logged out and logged in state)
- ✅ Note that after logging in, you are returned to the landing page (not the proposals table)
Closes #604 
Closes #561
=> Make orgs discoverable

src/App.css, src/components/BulkUploaderFilePicker.css, src/components/Button.css, src/components/Button.tsx, src/components/Dropdown/Dropdown.css, src/components/Dropdown/DropdownMenuButton.tsx, src/components/Dropdown/index.ts, src/components/FormElementGroup.css, src/components/User.tsx, src/index.css, src/stories/Dropdown.stories.tsx
This PR adds a user menu with a lone "Log out" link. That part was simple, but there were three prerequisite changes:
- Refactoring our `Button` component to extend native buttons for a cleaner prop definition
- Cleaning up our focus styling on interactive elements
- Adding a new `DropdownMenuButton` component so that dropdowns can contain links _or_ buttons
**Testing:**
1. Log in
2. Click your username in the top right and then the "Log out" button
3. ✅ You should be logged out and sent to the home page
4. Click "Log in"
5. ✅ You should be prompted to log in; if you aren't, and you're just round-tripped back to the PDC with a valid session, ❌ that's bad because it means we didn't kill the Keycloak session.
Resolves #619
=> Add user logout

package.json, src/components/Panel/Panel.css, src/components/ProposalListTablePanel.tsx, src/components/ToggleSwitch.css, src/components/ToggleSwitch.tsx, src/stories/ToggleSwitch.stories.tsx
This PR is the output of #620. It adds a new `ToggleSwitch` component in the style of iOS toggle switches (which have since broken out of iOS-land to be a pretty widely-used UI component, e.g. in [Tailwind](https://tailwindui.com/components/application-ui/forms/toggles) or [Bootstrap](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches)), and it converts our button-style wrapping toggle for the proposals table to use it, with the eventual aim of using it for "Show only my proposals" in #622.
**Before:**
https://github.com/PhilanthropyDataCommons/front-end/assets/4731/64d40b45-1732-4cb0-b5a5-0c8405e50ed8
**After:**
https://github.com/PhilanthropyDataCommons/front-end/assets/4731/76ddc449-067c-4052-a366-b1a60c4aa92b
- Examine the …
=> Convert Proposal's text-wrapper to a ToggleSwitch

src/pdc-api.ts
This PR scopes the bulk upload lists to only those created by the requesting user. It does so statically — i.e., without allowing the user to remove the scope and view bulk uploads from other people, even if they're authorized to. This is an intentional front-end UX choice until we build out a fuller interface for admins to see other people’s bulk uploads (if ever needed). It’s not a security concern; the API handles making sure users only see what they’re authorized to.
The `createdBy=me` value is a magic value that tells the API that the scope should be “the user ID of the requesting user”. That value doesn't work _yet_, but will once https://github.com/PhilanthropyDataCommons/service/pull/961 is merged.
**Testing:**
1. On `main`, on a multi-user system where multiple users have added …
=> Only show the user their own bulk uploads

src/components/Panel/Panel.css, src/components/ToggleSwitch.css
Two quick UI improvements that fix some rough edges:
- Toggle switches have heavier-weight labels to better distinguish them from content text
- Panel actions remain positioned in the top right of the panel even when the title wraps (with an exception for switches, which I'd like to improve in the future)
**Testing:**
- The "Wrap long text" toggle switch on `/proposals` was normal-weight, now it's heavy
- When drilling into an organization detail page at `/organization/:id`, the Data Provider button wasn't tucked neatly in the top right corner, it was down a bit; now it's neat
No associated issues, these are just little things noticed while testing.
=> Make some UI improvements

package-lock.json, package.json, src/components/OrganizationDetailPanel.tsx, src/components/OrganizationListGrid.tsx, src/components/OrganizationListTable.tsx, src/components/ProposalDetailPanel.tsx, src/pages/OrganizationDetail.tsx
This PR uses the new `taxId` attribute instead of the deprecated `employerIdentificationNumber`.
Resolves #723
=> Update EIN to Tax ID

src/pdc-api.ts
This PR fixes a type safety issue when building presigned post headers.
Related to #739
=> Guard presigned post field values

src/components/DataPlatformProvider/DataPlatformProviderLoader.tsx, src/pdc-api.ts
This PR uses the `PlatformProviderResponse` type from the SDK instead of defining our own.
In order to do this, we needed to disable the ESLint complaint about the `data` property being an `any`. ~This is allowable because in this ersatz implementation of a provider response, we don’t know the shape of the data.~ Update: This is not actually quite accurate. See updated context: https://github.com/PhilanthropyDataCommons/service/issues/1013#issuecomment-2120839690
**Testing:**
Just linting should do it. We actually aren't _using_ this type in a visible way, since the current batch of visible platform data is no longer available to the front-end.
Resolves #737
=> Use `PlatformProviderResponse` from SDK

src/components/ProposalListTable.tsx, src/components/ProposalListTablePanel.tsx, src/stories/ProposalListTable.stories.tsx
This commit removes the default values for rowClickDestination in the ProposalListTable and ProposalListTableRow components, and instead passes the PROPOSAL_DETAIL_PAGE value explicitly inside ProposalListTablePanel. This removes redundancy, and ensures that a value is always explicitly passed.
Closes #805
=> Set rowClickDestination value explicitly

src/components/BulkUploadListItem.tsx
This commit drops the initial value from the metadataElements reducer function, along with the conditional statement. As per the MDN docs[1], "if [no initial value is supplied,] the array element at index 0 is used as the initial value." Thus we don't need to specify an initial value, as we default to the first value, which, if it exists, is determined to be not null by the filter function.
Closes #803
=> Fix BulkUploadListItem metadata reducer

package.json
When we migrated to Vite in PR #748, we changed the output directory from `build` to `dist`. We (belatedly) updated our Netlify configuration to match this change, but in doing so left Storybook behind.
Update the output directory of Storybook to match, so that it is included in deploys.
=> Include Storybook in deploys

README.md, package-lock.json, package.json
Clean up the README and a few dependencies left over from create-react-app.
PR #856 Bump @babel/preset-typescript from 7.24.7 to 7.25.7
Follow-up to PR #748 Migrate to Vite
Issue #720 Move To Vite
=> Vite cleanup

.do/deploy.template.yaml, .env.example, README.md, netlify.toml, public/_redirects, src/components/AppNavbar.tsx
In order to deploy to DigitalOcean App Platform, we need to make one adjustment to the code, and add some documentation.
Since this is currently deployed to Netlify, it seems to be about time to add a "Deploy to Netlify" button, and then a "Deploy to DigitalOcean" button next to it. (I wish they were the same size, but not sure how to do that in markdown.)
Issue PhilanthropyDataCommons/deploy#118 Migrate to DigitalOcean Apps
=> Deploy to DigitalOcean App Platform

src/components/ChangemakerProposal/ChangemakerProposalLoader.tsx, src/components/ChangemakerProposal/ChangemakerProposalPanel.tsx, src/components/Panel/ClosablePanel.tsx, src/components/ProposalDetailPanel.tsx, src/pages/ProposalDetail.tsx, src/stories/ProposalDetail.stories.tsx
This commit adds the rendering for a given proposal version's Source, following the same pattern as we currently use for applicant and tax ID (the Panel Tag component).
Closes #913
=> Add source label to proposal version

.github/dependabot.yml
This PR groups react dependencies in dependabot more aggressively, which addresses the broken dependabot PRs we're seeing right now.
=> Group react more aggressively

.eslintrc.json, package.json
This commit separates the eslintConfig into it's own file, which has been our preferred method of configuration in the PDC service repository for over a year. Furthermore, this will more elegantly support our move to eslint9, which expects a flat configuration file by default.
Closs #994
=> Move configuration out of package.json

.do/deploy.template.yaml
This PR updates the environment variables in our digital ocean deploy.template.yaml file to the correct values, after they were changed in Issue #1009. It also includes the addition of the `VITE_KEYCLOAK_REALM` variable, which is a new requirement from the `@dsb-norge/vue-keycloak-js` keycloak connector package we are using, requiring the keycloak realm as an explicit variable.
Closes #1054
=> Update environment variables in DO template file

env.d.ts, eslint.config.mjs, src/components/AppBanner.vue, src/components/CustomButton.vue, src/components/Dropdown/DropdownMenuButton.vue, src/components/Dropdown/DropdownMenuLink.vue, src/components/Dropdown/DropdownTrigger.vue, src/components/EmailLink.vue, src/components/UserComponent.vue, src/keycloakConfig.ts, src/main.ts, src/pdc-api.ts, src/reportWebVitals.ts, src/router.ts, src/utils/baseFields.ts, src/utils/datetime.ts, src/views/LandingView.vue
This PR re-enables all the rules that we disabled on introduction of the love ESLint config, linting the codebase commit by commit. 
[ Re-enable @typescript-eslint/no-unnecessary-type-parameters](https://github.com/PhilanthropyDataCommons/front-end/commit/b62708f8e091cdb443b5762b616ba2e1e26f5331) includes a large write up, mostly detailing this info for 'if this comes up again' purposes. It's a small change but took a long time to resolve/understand what was going on under the hood better. It also brought up to me that I may want to rethink/research the proper data fetching/re-fetching patterns in vue for this function and future functions.
Closes #1056
=> Re-enable love rules

apps/admin-interface/vite.config.ts, apps/bulk-uploader/vite.config.ts, packages/components/src/components/Table/TableBody.vue, packages/components/src/components/Table/TableColumnAction.vue, packages/components/src/components/Table/TableColumnActions.vue, packages/components/src/components/Table/TableColumnHead.vue, packages/components/src/components/Table/TableComponent.vue, packages/components/src/components/Table/TableHead.vue, packages/components/src/components/Table/TableRow.vue, packages/components/src/components/Table/TableRowCell.vue, packages/components/src/components/Table/index.ts, packages/components/src/index.ts, packages/components/src/stories/TableComponent.stories.ts
This commit adds a suite of table related components, modeled after the table components that we built in the previous version of this application for rendering data from the pdc in a row/column format. They are intended to be used in both the bulk-uploader and base field admin applications, and are extendable to any data type in the pdc we may wish to render as such.
Column actions are intended to house future logic for sorting and filtering the data in tables. Those will be accomplished in a future commit.
Related to Issue #1068
=> Create table components

apps/bulk-uploader/src/views/LandingView.vue, packages/components/src/components/DataInputs/DataSubmitButton.vue, packages/components/src/components/DataInputs/FileUploadInput.vue, packages/components/src/components/DataInputs/RadioInput.vue, packages/components/src/components/DataInputs/SelectInput.vue, packages/components/src/components/DataInputs/index.ts, packages/components/src/components/Panel/PanelBody.vue, packages/components/src/components/Panel/PanelComponent.vue, packages/components/src/components/Panel/PanelHeader.vue, packages/components/src/components/Panel/PanelSection.vue, packages/components/src/components/Panel/index.ts, packages/components/src/index.ts, packages/components/src/stories/DataSubmitButton.stories.ts, packages/components/src/stories/FileUploadInput.stories.ts, packages/components/src/stories/RadioInput.stories.ts, packages/components/src/stories/SelectInput.stories.ts, packages/components/src/stories/TableComponent.stories.ts
These commits add in extendable dataInput components for constructing forms in the PDC for data upload. They are currently only the types of forms we'll be using in the bulk-uploader (file upload, radio, and select forms), but are already intended to be used in the base-field admin interface. It also adds the optional rendering of Panels as DataInput panels, which have their own stylings consistent across applications. 
Closes Issue #1093
=> Implement data input components

apps/bulk-uploader/src/components/BaseFieldsTable.vue, apps/bulk-uploader/src/components/BulkUploader.vue, apps/bulk-uploader/src/pdc-api.ts, apps/bulk-uploader/src/router.ts, apps/bulk-uploader/src/views/AddDataView.vue, apps/bulk-uploader/src/views/LandingView.vue, packages/utilities/src/api-hooks.ts, packages/utilities/src/index.ts
This PR adds a view for adding bulk uploads to the PDC, bringing together the work we did in #1110 to support data upload, as well as adding a suite of necessary api hooks. It is heavily modeled off of the workflow we'd designed for the [previous iteration of the application](https://github.com/PhilanthropyDataCommons/front-end/blob/b1dcd3a4960ccd014a4dc0a6101431f079f69ace/src/pdc-api.ts). 
Closes #1066
=> Implement bulk uploader add data view

apps/admin-interface/package.json, apps/bulk-uploader/package.json, apps/bulk-uploader/src/pdc-api.ts, apps/bulk-uploader/src/views/AddDataView.vue, package-lock.json, packages/components/package.json, packages/utilities/package.json
This commit changes all references from PresignedPostRequests to the new File entity, as defined in service issue #1689. The functionality of the two entities are the same, so the only changes needed to be made are in the naming of our hooks and the route we're calling.
Closes #1127
=> Update PresignedPostRequest to File

apps/bulk-uploader/src/components/BulkUploader.vue
This commit makes an explicit note of the requirement of the proposal submitter email field in a bulk-upload, as bulk-uploads without that field will fail.
Closes #1167
=> Make explicit note of proposal submitter email field
